name: "Minesweeper"

on:
    issues:
        types: [opened]

jobs:
    minesweeper:
        runs-on: ubuntu-latest
        if: startsWith(github.event.issue.title, 'minesweeper:')
        steps:
        
        # Setup Python first
        - name: Setup Python
          uses: actions/setup-python@v2.2.1
          with:
            python-version: 3.7
    
        - name: Clone repos
          run: |
            git clone https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/raspiduino
            git clone https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/minesweeper_readme
        
        # Install require libs
        - name: Install required libraries
          run: |
            pip3 install PyGithub
    
        - name: Run Python script
        # Time for Python codee
          run: |
            cd raspiduino
            MYACCESSTOKEN=${{ secrets.MY_ACCESS_TOKEN }} python3 minesweeper.py
        
        - name: Push the data back to the repo
          run : |
            cd ..
            cd minesweeper_readme
            git add .
            git commit -m "Update data"
            git remote set-url origin https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/minesweeper_readme
            git push -f origin main
              
