name: "Minesweeper"

on:
    issues:
        types: [opened]

concurrency: minesweeper-main

jobs:
    minesweeper:
        runs-on: ubuntu-latest
        if: startsWith(github.event.issue.title, 'minesweeper:')
        steps:
        
        # Setup Python first
        - name: Setup Python
          uses: actions/setup-python@v2.2.1
          with:
            python-version: 3.7
    
        - name: Clone repos
          run: |
            git clone https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/raspiduino
            git clone https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/minesweeper_readme
        
        # Install require libs
        - name: Install required libraries
          run: |
            pip3 install PyGithub
    
        - name: Run Python script
        # Time for Python codee
          run: |
            MYACCESSTOKEN=${{ secrets.MY_ACCESS_TOKEN }} python3 raspiduino/minesweeper.py
              
        - name: Push the data back to the main repo
          run : |
            cd raspiduino
            git remote set-url origin https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/raspiduino
            git config --global user.email "raspiduinogit@gmail.com"
            git config --global user.name "Raspiduino"
            git add .
            git commit -m "Update the minesweeper game"
            git push -f origin main
            
        - name: Push the data to gamedata repo
          run: |
            cd minesweeper_readme
            git remote set-url origin https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/minesweeper_readme
            git config --global user.email "raspiduinogit@gmail.com"
            git config --global user.name "Raspiduino"
            git add .
            git diff-index --quiet HEAD || git commit -m "Update gamedata"
            git push -f origin main
